CREATE TABLE TIPOS_PESSOA
(ID INTEGER NOT NULL PRIMARY KEY,
DESCRICAO CHAR(20));

CREATE TABLE PESSOA
(NOME VARCHAR(128) PRIMARY KEY,
TELEFONE VARCHAR(64) DEFAULT '(XX)XXXX.XXXX',
EMAIL VARCHAR(128),
TIPOS_PESSOA_ID INTEGER);

INSERT INTO TIPOS_PESSOA VALUES(1, 'Fisica'); 
INSERT INTO TIPOS_PESSOA VALUES(2, 'Juridica');

INSERT INTO PESSOA VALUES ('Francisco', '(85)123.456.789', 'francisco@gmail.com', 1);
INSERT INTO PESSOA VALUES ('Joao', '(85)1234.5678', 'joao@gmail.com', 1);
INSERT INTO PESSOA VALUES ('Pizzaria do Jaoa', '(85)123.456.789', 'contato@pizzariadojoao.com', 2);